### ISSUE TITLE
Switch core to net/netip, new netip.Addr API, maintain legacy API

### ISSUE THREAD

**Issue by jpillora** [phuslu/iploc#9]
Tailscale got this merged into stdlib. Read more https://tailscale.com/blog/netaddr-new-ip-type-for-go

**Comment by phuslu** [comment]
thanks, working on it.

**Comment by phuslu** [comment]
v1.0.20240311 tagged, thanks.

**Comment by jpillora** [comment]
Thanks! Will take a look soon :)
